# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

stages:
  - stage: Builds
    displayName: Build artifacts to be deployed
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    jobs:
      - job: BuildDotNetDesktop
        displayName: Build the database scehma's dacpac
        pool:
          vmImage: 'windows-latest'
        steps:
        - task: NuGetToolInstaller@1
        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'
        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        - task: VSTest@2
          inputs:
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
            
  - stage: Deployments
    displayName: Deploy artifacts to Azure
    jobs:
      - deployment: DeployDatabase
        displayName: Deploy database schema changes to Azure
        pool:
          vmImage: 'windows-latest'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: SqlAzureDacpacDeployment@1
                inputs:
                  azureSubscription: 'Assaf''s Microsoft Azure Internal Consumption(d98ee679-4c4d-4a03-9181-ea7a16d0b5a8)'
                  AuthenticationType: 'server'
                  ServerName: 'awdemo4teck.database.windows.net'
                  DatabaseName: 'AdventureWorks2016'
                  SqlUsername: 'assaf'
                  SqlPassword: 'AWDBP@ssw0rd!'
                  deployType: 'DacpacTask'
                  DeploymentAction: 'Publish'
                  IpDetectionMethod: 'AutoDetect'